[book]
authors = ["lab-xps-pc"]
language = "en"
multilingual = false
src = "src"
title = "AIROU Documentation"

[output.html]
edit-url-template = "https://github.com/airou-lab/air-lab-documentation/edit/master/{path}"
git-repository-url = "https://github.com/airou-lab/air-lab-documentation/"