[book]
authors = ["Tyler Roman", "Matthew Carroll"]
language = "en"
multilingual = false
src = "src"
title = "AIROU Documentation"

[build]
create-missing = false

[output.html]
edit-url-template = "https://github.com/airou-lab/docs/edit/master/{path}"
git-repository-url = "https://github.com/airou-lab/docs/"